<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] Q: PyQt and error handling in Deferreds
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20Q%3A%20PyQt%20and%20error%20handling%20in%20Deferreds&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="004731.html">
   <LINK REL="Next"  HREF="004702.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] Q: PyQt and error handling in Deferreds</H1>
    <B>Egor Cheshkov</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20Q%3A%20PyQt%20and%20error%20handling%20in%20Deferreds&In-Reply-To="
       TITLE="[Twisted-Python] Q: PyQt and error handling in Deferreds">egor at iplus.ru
       </A><BR>
    <I>Tue Jun 24 05:20:53 EDT 2003</I>
    <P><UL>
        <LI>Previous message: <A HREF="004731.html">[Twisted-Python] Getting Stories Straight (RPYs)
</A></li>
        <LI>Next message: <A HREF="004702.html">[Twisted-Python] Q: PyQt and error handling in Deferreds
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#4700">[ date ]</a>
              <a href="thread.html#4700">[ thread ]</a>
              <a href="subject.html#4700">[ subject ]</a>
              <a href="author.html#4700">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hello!

I'm writing client application using Twisted and PyQt. I want to handle 
connection errors by showing the message box that describes it, so my errback  
looks like this:

    def _ebSessionRequest(self, err):
        QMessageBox.critical(self, &quot;Warder&quot;, &quot;Can't connect to server.&quot;)
        self.setEnabled(1)
        self.editAccesCode.setFocus()

It works nice but when the errback fired i get two tracebacks:

Traceback (most recent call last):
  File &quot;/usr/lib/python2.2/site-packages/twisted/internet/defer.py&quot;, line 215, 
in errback
    self._startRunCallbacks(fail, 1)
  File &quot;/usr/lib/python2.2/site-packages/twisted/internet/defer.py&quot;, line 249, 
in _startRunCallbacks
    self._runCallbacks()
  File &quot;/usr/lib/python2.2/site-packages/twisted/internet/defer.py&quot;, line 262, 
in _runCallbacks
    self.result = callback(self.result, *args, **kw)
  File &quot;main.py&quot;, line 185, in _ebSessionRequest
    QMessageBox.critical(self, &quot;Warder&quot;, &quot;Can't connect to server.&quot;)
--- &lt;exception caught here&gt; ---
  File &quot;/usr/lib/python2.2/site-packages/twisted/internet/qtreactor.py&quot;, line 
74, in read
    why = w.doRead()
  File &quot;/usr/lib/python2.2/site-packages/twisted/internet/tcp.py&quot;, line 378, 
in doConnect
    self.failIfNotConnected(error.getConnectError((connectResult, 
os.strerror(connectResult))))
  File &quot;/usr/lib/python2.2/site-packages/twisted/internet/tcp.py&quot;, line 315, 
in failIfNotConnected
    self.connector.connectionFailed(failure.Failure(err))
  File &quot;/usr/lib/python2.2/site-packages/twisted/internet/base.py&quot;, line 527, 
in connectionFailed
    self.factory.clientConnectionFailed(self, reason)
  File &quot;/usr/lib/python2.2/site-packages/twisted/web/xmlrpc.py&quot;, line 209, in 
clientConnectionLost
    self.deferred.errback(reason)
  File &quot;/usr/lib/python2.2/site-packages/twisted/internet/defer.py&quot;, line 215, 
in errback
    self._startRunCallbacks(fail, 1)
  File &quot;/usr/lib/python2.2/site-packages/twisted/internet/defer.py&quot;, line 240, 
in _startRunCallbacks
    raise AlreadyCalledError()
twisted.internet.defer.AlreadyCalledError:
Traceback (most recent call last):
  File &quot;/usr/lib/python2.2/site-packages/twisted/internet/defer.py&quot;, line 215, 
in errback
    self._startRunCallbacks(fail, 1)
  File &quot;/usr/lib/python2.2/site-packages/twisted/internet/defer.py&quot;, line 249, 
in _startRunCallbacks
    self._runCallbacks()
  File &quot;/usr/lib/python2.2/site-packages/twisted/internet/defer.py&quot;, line 262, 
in _runCallbacks
    self.result = callback(self.result, *args, **kw)
  File &quot;main.py&quot;, line 185, in _ebSessionRequest
    QMessageBox.critical(self, &quot;Warder&quot;, &quot;Can't connect to server.&quot;)
--- &lt;exception caught here&gt; ---
  File &quot;/usr/lib/python2.2/site-packages/twisted/internet/qtreactor.py&quot;, line 
83, in read
    w.connectionLost(failure.Failure(why))
  File &quot;/usr/lib/python2.2/site-packages/twisted/internet/tcp.py&quot;, line 396, 
in connectionLost
    self.failIfNotConnected(error.ConnectError())
  File &quot;/usr/lib/python2.2/site-packages/twisted/internet/tcp.py&quot;, line 315, 
in failIfNotConnected
    self.connector.connectionFailed(failure.Failure(err))
  File &quot;/usr/lib/python2.2/site-packages/twisted/internet/base.py&quot;, line 527, 
in connectionFailed
    self.factory.clientConnectionFailed(self, reason)
  File &quot;/usr/lib/python2.2/site-packages/twisted/web/xmlrpc.py&quot;, line 209, in 
clientConnectionLost
    self.deferred.errback(reason)
  File &quot;/usr/lib/python2.2/site-packages/twisted/internet/defer.py&quot;, line 215, 
in errback
    self._startRunCallbacks(fail, 1)
  File &quot;/usr/lib/python2.2/site-packages/twisted/internet/defer.py&quot;, line 240, 
in _startRunCallbacks
    raise AlreadyCalledError()
twisted.internet.defer.AlreadyCalledError:

My question is: is it normal? How can I avoid such tracebacks?


-- 
Egor Cheshkov &lt;<A HREF="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">egor at iplus.ru</A>&gt;




</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="004731.html">[Twisted-Python] Getting Stories Straight (RPYs)
</A></li>
	<LI>Next message: <A HREF="004702.html">[Twisted-Python] Q: PyQt and error handling in Deferreds
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#4700">[ date ]</a>
              <a href="thread.html#4700">[ thread ]</a>
              <a href="subject.html#4700">[ subject ]</a>
              <a href="author.html#4700">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
