<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] mishandling windows connect error
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20mishandling%20windows%20connect%20error&In-Reply-To=%3C5567FCC8-964D-11D7-B9B9-000393C92466%40dalkescientific.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=utf-8">
   <LINK REL="Previous"  HREF="036886.html">
   <LINK REL="Next"  HREF="036885.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] mishandling windows connect error</H1>
    <B>Andrew Dalke</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20mishandling%20windows%20connect%20error&In-Reply-To=%3C5567FCC8-964D-11D7-B9B9-000393C92466%40dalkescientific.com%3E"
       TITLE="[Twisted-Python] mishandling windows connect error">dalke at dalkescientific.com
       </A><BR>
    <I>Tue Jun  3 23:28:12 MDT 2003</I>
    <P><UL>
        <LI>Previous message (by thread): <A HREF="036886.html">[Twisted-Python] creds and xmlrpc
</A></li>
        <LI>Next message (by thread): <A HREF="036885.html">[Twisted-Python] mishandling windows connect error
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#36877">[ date ]</a>
              <a href="thread.html#36877">[ thread ]</a>
              <a href="subject.html#36877">[ subject ]</a>
              <a href="author.html#36877">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>That error report I made earlier this evening is not reproducible under
Linux.  It's only under MS Windows.

Here's some more information.  Twisted isn't reporting the correct
error message for when a TCP connection fails under MS Windows.

Here's the reproducible

E:\dalke&gt;..\Python22\python.exe
Python 2.2.3c1 (#41, May 22 2003, 19:16:28) [MSC 32 bit (Intel)] on 
win32
Type &quot;help&quot;, &quot;copyright&quot;, &quot;credits&quot; or &quot;license&quot; for more information.
 &gt;&gt;&gt; from twisted.web.xmlrpc import Proxy
 &gt;&gt;&gt; from twisted.internet import reactor
 &gt;&gt;&gt; def printValue(value):
...   print value
...   reactor.stop()
...
 &gt;&gt;&gt; proxy = Proxy(&quot;<A HREF="http://beatty.userland.com:34686">http://beatty.userland.com:34686</A>&quot;)
 &gt;&gt;&gt; proxy.callRemote('test.sumprod', 3, 5).addCallbacks(printValue, 
printValue)
&lt;Deferred at 0xc38f40&gt;
 &gt;&gt;&gt; reactor.run()
[Failure instance: Traceback: twisted.internet.error.ConnectError, [160]
]
 &gt;&gt;&gt;

Under Linux, this reports &quot;Connection refused&quot; as expected.

The ConnectError contains the value [160].  Looking at the stack trace, 
I found
it was created in tcp.py in BaseClient.doConnect where it says

         # on windows failed connects are reported on exception
         # list, not write or read list.
         if platform.getType() == &quot;win32&quot;:
             r, w, e = select.select([], [], [self.fileno()], 0.0)
             if e:
                 self.failIfNotConnected(error.getConnectError(e))
                 return

If there is an error then 'e' will contain a list of size one, which is
the fileno.  Now look at the getConnectError definition in 
internet/error.py

def getConnectError(e):
     &quot;&quot;&quot;Given a socket exception, return connection error.&quot;&quot;&quot;
     try:
         number, string = e
     except ValueError:
         return ConnectError(string=e)

This will always give a ValueError (list of size 1 can't be assigned to
two terms) so it returns a ConnectError with the 'string' set to the
single element list.

And this is the '[160]' reported in the ConnectError of the failure,
which means it was on fileno 160.

I do not claim to be a network person.  It's all confusing to me.  I
tried commenting out that block, to see what the connect_ex does.
It returns a EWOULDBLOCK.  That's as far as I took it.

It feels to me like there's a bug around there someplace.

					Andrew
					<A HREF="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">dalke at dalkescientific.com</A>



</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message (by thread): <A HREF="036886.html">[Twisted-Python] creds and xmlrpc
</A></li>
	<LI>Next message (by thread): <A HREF="036885.html">[Twisted-Python] mishandling windows connect error
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#36877">[ date ]</a>
              <a href="thread.html#36877">[ thread ]</a>
              <a href="subject.html#36877">[ subject ]</a>
              <a href="author.html#36877">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
