<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] TaskStopped error,	unsure of the cause and solution
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20TaskStopped%20error%2C%0A%09unsure%20of%20the%20cause%20and%20solution&In-Reply-To=%3CCACgdh2iF3q2xkT4XShQCRCctLu1cQNGtCdOkA2GRn2DfoNxQLg%40mail.gmail.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=utf-8">
   <LINK REL="Previous"  HREF="059003.html">
   <LINK REL="Next"  HREF="059006.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] TaskStopped error,	unsure of the cause and solution</H1>
    <B>Paul Wiseman</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20TaskStopped%20error%2C%0A%09unsure%20of%20the%20cause%20and%20solution&In-Reply-To=%3CCACgdh2iF3q2xkT4XShQCRCctLu1cQNGtCdOkA2GRn2DfoNxQLg%40mail.gmail.com%3E"
       TITLE="[Twisted-Python] TaskStopped error,	unsure of the cause and solution">poalman at gmail.com
       </A><BR>
    <I>Fri Feb  8 08:12:58 MST 2013</I>
    <P><UL>
        <LI>Previous message (by thread): <A HREF="059003.html">[Twisted-Python] Perspective Broker system into a TCP Listener
</A></li>
        <LI>Next message (by thread): <A HREF="059006.html">[Twisted-Python] TaskStopped error, unsure of the cause and solution
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#59005">[ date ]</a>
              <a href="thread.html#59005">[ thread ]</a>
              <a href="subject.html#59005">[ subject ]</a>
              <a href="author.html#59005">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>On 27 December 2012 14:49, Paul Wiseman &lt;<A HREF="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">poalman at gmail.com</A>&gt; wrote:
&gt;<i> On 21 December 2012 18:08,  &lt;<A HREF="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">exarkun at twistedmatrix.com</A>&gt; wrote:
</I>&gt;&gt;<i> On 04:12 pm, <A HREF="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">poalman at gmail.com</A> wrote:
</I>&gt;&gt;&gt;<i>Hey,
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>I'm getting the following error in my logs (lots and lots), but only
</I>&gt;&gt;&gt;<i>after the server has been running for some time, I'm not sure what the
</I>&gt;&gt;&gt;<i>cause is or what I can do to remedy it.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> This seems like a bug in `Agent`, perhaps related to `stopProducing`
</I>&gt;&gt;<i> being called more than once.  It would be great if you could produce a
</I>&gt;&gt;<i> minimal example to include with a bug report in the issue tracker.  An
</I>&gt;&gt;<i> example that reproduces the problem will also make it easier to see
</I>&gt;&gt;<i> where the bug is in your code, if it happens to be there rather than in
</I>&gt;&gt;<i> Twisted.
</I>&gt;<i>
</I>&gt;<i> I'll try my best! The problem is I don't seem to see this at all for
</I>&gt;<i> 10k+ requests ish then I guess something must trigger it as it will
</I>&gt;<i> start happening a lot, so it may be difficult to reproduce.
</I>&gt;<i>
</I>
I've still not been able to reproduce this on demand.. the least
amount of request I've seen before getting the error is 6500 :/

I've also seen this stack trace which I didn't notice before

2013-02-08 10:07:28+0000 [HTTP11ClientProtocol,client] Unhandled Error
        Traceback (most recent call last):
          File &quot;/usr/local/lib/python2.7/dist-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/application/app.py&quot;,
line 323, in runReactorWithLogging
            reactor.run()
          File &quot;/usr/local/lib/python2.7/dist-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/base.py&quot;,
line 1169, in run
            self.mainLoop()
          File &quot;/usr/local/lib/python2.7/dist-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/base.py&quot;,
line 1181, in mainLoop
            self.doIteration(t)
          File &quot;/usr/local/lib/python2.7/dist-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/epollreactor.py&quot;,
line 379, in doPoll
            log.callWithLogger(selectable, _drdw, selectable, fd, event)
        --- &lt;exception caught here&gt; ---
          File &quot;/usr/local/lib/python2.7/dist-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/python/log.py&quot;,
line 84, in callWithLogger
            return callWithContext({&quot;system&quot;: lp}, func, *args, **kw)
          File &quot;/usr/local/lib/python2.7/dist-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/python/log.py&quot;,
line 69, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File &quot;/usr/local/lib/python2.7/dist-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/python/context.py&quot;,
line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File &quot;/usr/local/lib/python2.7/dist-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/python/context.py&quot;,
line 81, in callWithContext
            return func(*args,**kw)
          File &quot;/usr/local/lib/python2.7/dist-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/posixbase.py&quot;,
line 639, in _doReadOrWrite
            self._disconnectSelectable(selectable, why, inRead)
          File &quot;/usr/local/lib/python2.7/dist-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/posixbase.py&quot;,
line 258, in _disconnectSelectable
            selectable.readConnectionLost(f)
          File &quot;/usr/local/lib/python2.7/dist-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py&quot;,
line 267, in readConnectionLost
            self.connectionLost(reason)
          File &quot;/usr/local/lib/python2.7/dist-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py&quot;,
line 473, in connectionLost
            self._commonConnection.connectionLost(self, reason)
          File &quot;/usr/local/lib/python2.7/dist-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py&quot;,
line 281, in connectionLost
abstract.FileDescriptor.connectionLost(self, reason)
          File &quot;/usr/local/lib/python2.7/dist-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/abstract.py&quot;,
line 182, in connectionLost            self.producer.stopProducing()
          File &quot;/usr/local/lib/python2.7/dist-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/web/client.py&quot;,
line 760, in stopProducing            self._task.stop()
          File &quot;/usr/local/lib/python2.7/dist-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/task.py&quot;,
line 460, in stop            self._completeWith(TaskStopped(),
Failure(TaskStopped()))
          File &quot;/usr/local/lib/python2.7/dist-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/task.py&quot;,
line 439, in _completeWith
self._cooperator._removeTask(self)
          File &quot;/usr/local/lib/python2.7/dist-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/task.py&quot;,
line 578, in _removeTask            self._delayedCall.cancel()
          File &quot;/usr/local/lib/python2.7/dist-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/base.py&quot;,
line 89, in cancel
            raise error.AlreadyCalled
        twisted.internet.error.AlreadyCalled: Tried to cancel an
already-called event.

I'll keep trying to work out the issue, any suggestions on what I
might try to reproduce it or guesses at causes?

&gt;&gt;<i>
</I>&gt;&gt;<i> Jean-Paul
</I>&gt;&gt;&gt;<i>This is what I see in the logs:
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>2012-12-20 17:07:17+0000 [HTTP11ClientProtocol,client] Unhandled Error
</I>&gt;&gt;&gt;<i>        Traceback (most recent call last):
</I>&gt;&gt;&gt;<i>        Failure: twisted.web._newclient.RequestTransmissionFailed:
</I>&gt;&gt;&gt;<i>[&lt;twisted.python.failure.Failure &lt;class
</I>&gt;&gt;&gt;<i>'twisted.internet.error.ConnectionDone'&gt;&gt;]
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>2012-12-20 17:07:17+0000 [HTTP11ClientProtocol,client] Unexpected
</I>&gt;&gt;&gt;<i>exception from twisted.web.client.FileBodyProducer.stopProducing
</I>&gt;&gt;&gt;<i>        Traceback (most recent call last):
</I>&gt;&gt;&gt;<i>          File &quot;/usr/local/lib/python2.7/site-
</I>&gt;&gt;&gt;<i>packages/Twisted-12.2.0-py2.7-linux-
</I>&gt;&gt;&gt;<i>x86_64.egg/twisted/internet/endpoints.py&quot;,
</I>&gt;&gt;&gt;<i>line 99, in connectionLost
</I>&gt;&gt;&gt;<i>            return self._wrappedProtocol.connectionLost(reason)
</I>&gt;&gt;&gt;<i>          File &quot;/usr/local/lib/python2.7/site-
</I>&gt;&gt;&gt;<i>packages/Twisted-12.2.0-py2.7-linux-
</I>&gt;&gt;&gt;<i>x86_64.egg/twisted/web/_newclient.py&quot;,
</I>&gt;&gt;&gt;<i>line 859, in dispatcher
</I>&gt;&gt;&gt;<i>            return func(*args, **kwargs)
</I>&gt;&gt;&gt;<i>          File &quot;/usr/local/lib/python2.7/site-
</I>&gt;&gt;&gt;<i>packages/Twisted-12.2.0-py2.7-linux-
</I>&gt;&gt;&gt;<i>x86_64.egg/twisted/web/_newclient.py&quot;,
</I>&gt;&gt;&gt;<i>line 1458, in _connectionLost_TRANSMITTING
</I>&gt;&gt;&gt;<i>            self._currentRequest.stopWriting()
</I>&gt;&gt;&gt;<i>          File &quot;/usr/local/lib/python2.7/site-
</I>&gt;&gt;&gt;<i>packages/Twisted-12.2.0-py2.7-linux-
</I>&gt;&gt;&gt;<i>x86_64.egg/twisted/web/_newclient.py&quot;,
</I>&gt;&gt;&gt;<i>line 760, in stopWriting
</I>&gt;&gt;&gt;<i>            _callAppFunction(self.bodyProducer.stopProducing)
</I>&gt;&gt;&gt;<i>        --- &lt;exception caught here&gt; ---
</I>&gt;&gt;&gt;<i>          File &quot;/usr/local/lib/python2.7/site-
</I>&gt;&gt;&gt;<i>packages/Twisted-12.2.0-py2.7-linux-
</I>&gt;&gt;&gt;<i>x86_64.egg/twisted/web/_newclient.py&quot;,
</I>&gt;&gt;&gt;<i>line 191, in _callAppFunction
</I>&gt;&gt;&gt;<i>            function()
</I>&gt;&gt;&gt;<i>          File &quot;/usr/local/lib/python2.7/site-
</I>&gt;&gt;&gt;<i>packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/web/client.py&quot;,
</I>&gt;&gt;&gt;<i>line 760, in stopProducing
</I>&gt;&gt;&gt;<i>            self._task.stop()
</I>&gt;&gt;&gt;<i>          File &quot;/usr/local/lib/python2.7/site-
</I>&gt;&gt;&gt;<i>packages/Twisted-12.2.0-py2.7-linux-
</I>&gt;&gt;&gt;<i>x86_64.egg/twisted/internet/task.py&quot;,
</I>&gt;&gt;&gt;<i>line 459, in stop
</I>&gt;&gt;&gt;<i>            self._checkFinish()
</I>&gt;&gt;&gt;<i>          File &quot;/usr/local/lib/python2.7/site-
</I>&gt;&gt;&gt;<i>packages/Twisted-12.2.0-py2.7-linux-
</I>&gt;&gt;&gt;<i>x86_64.egg/twisted/internet/task.py&quot;,
</I>&gt;&gt;&gt;<i>line 469, in _checkFinish
</I>&gt;&gt;&gt;<i>            raise self._completionState
</I>&gt;&gt;&gt;<i>        twisted.internet.task.TaskStopped:
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>Just loads of those, they always seem to come through in pairs (the
</I>&gt;&gt;&gt;<i>first twisted.internet.error.ConnectionDone, and then the
</I>&gt;&gt;&gt;<i>twisted.internet.task.TaskStopped as above)
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>I'm just doing PUT requests with twisted.web.client.Agent and using a
</I>&gt;&gt;&gt;<i>twisted.web.client.FileBodyProducer to provide the content.
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>I'm doing the PUT while I still have the request from a render_GET, so
</I>&gt;&gt;&gt;<i>I thought maybe it's caused if the user disconnects while I'm doing
</I>&gt;&gt;&gt;<i>the PUT? The idea is I redirect them to the file I PUT with
</I>&gt;&gt;&gt;<i>request.redirect, which seems to work fine (until I get this error and
</I>&gt;&gt;&gt;<i>it doesn't)
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>The reason I do a PUT and redirect, instead of just writing back to
</I>&gt;&gt;&gt;<i>the request is that I check if the file is in a cache first, I then
</I>&gt;&gt;&gt;<i>only PUT if it's not there- then redirect afterwards.
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>Any clues or ideas of what is happening would be hugely helpful
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>thanks!!
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>Paul
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>_______________________________________________
</I>&gt;&gt;&gt;<i>Twisted-Python mailing list
</I>&gt;&gt;&gt;<i><A HREF="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">Twisted-Python at twistedmatrix.com</A>
</I>&gt;&gt;&gt;<i><A HREF="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python</A>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> _______________________________________________
</I>&gt;&gt;<i> Twisted-Python mailing list
</I>&gt;&gt;<i> <A HREF="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">Twisted-Python at twistedmatrix.com</A>
</I>&gt;&gt;<i> <A HREF="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python</A>
</I>

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message (by thread): <A HREF="059003.html">[Twisted-Python] Perspective Broker system into a TCP Listener
</A></li>
	<LI>Next message (by thread): <A HREF="059006.html">[Twisted-Python] TaskStopped error, unsure of the cause and solution
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#59005">[ date ]</a>
              <a href="thread.html#59005">[ thread ]</a>
              <a href="subject.html#59005">[ subject ]</a>
              <a href="author.html#59005">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
