<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] Unit tests, inline callbacks,	and exception handling
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20Unit%20tests%2C%20inline%20callbacks%2C%0A%09and%20exception%20handling&In-Reply-To=%3C6967807B-9839-4D28-A64A-BFE726EB28B5%40priority5.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=utf-8">
   <LINK REL="Previous"  HREF="053014.html">
   <LINK REL="Next"  HREF="053016.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] Unit tests, inline callbacks,	and exception handling</H1>
    <B>Patrick Hartling</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20Unit%20tests%2C%20inline%20callbacks%2C%0A%09and%20exception%20handling&In-Reply-To=%3C6967807B-9839-4D28-A64A-BFE726EB28B5%40priority5.com%3E"
       TITLE="[Twisted-Python] Unit tests, inline callbacks,	and exception handling">patrick at priority5.com
       </A><BR>
    <I>Thu Sep 24 11:04:07 MDT 2009</I>
    <P><UL>
        <LI>Previous message (by thread): <A HREF="053014.html">[Twisted-Python] Unit tests, inline callbacks,	and exception handling
</A></li>
        <LI>Next message (by thread): <A HREF="053016.html">[Twisted-Python] Unit tests, inline callbacks,	and exception handling
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#53015">[ date ]</a>
              <a href="thread.html#53015">[ thread ]</a>
              <a href="subject.html#53015">[ subject ]</a>
              <a href="author.html#53015">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>On Sep 24, 2009, at 11:59 AM, <A HREF="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">exarkun at twistedmatrix.com</A> wrote:

&gt;<i> On 04:51 pm, <A HREF="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">patrick at priority5.com</A> wrote:
</I>&gt;&gt;<i> We are using nose and the twisted.trial.unittest.TestCase class from
</I>&gt;&gt;<i> Twisted 8.2.0 to write tests that use inline callbacks. In one of the
</I>&gt;&gt;<i> tests, we are trying to validate that the code will behave correctly
</I>&gt;&gt;<i> by raising an exception if two clients with the same user name  
</I>&gt;&gt;<i> connect
</I>&gt;&gt;<i> to a server. The basic test code is similar to this:
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> @inlineCallbacks
</I>&gt;&gt;<i> def testDuplicateConnect(self):
</I>&gt;&gt;<i>   server_port = random.randint(10000, 40000)
</I>&gt;&gt;<i>   server = Server()
</I>&gt;&gt;<i>   server.listen(port = server_port)
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>   client1 = Client(username = &quot;Test&quot;)
</I>&gt;&gt;<i>   yield client1.connect(port = server_port)
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>   try:
</I>&gt;&gt;<i>      client2 = Client(username = &quot;Test&quot;)
</I>&gt;&gt;<i>      yield client2.connect(port = server_port)
</I>&gt;&gt;<i>      assert False
</I>&gt;&gt;<i>   except UsernameAlreadyExists, ex:
</I>&gt;&gt;<i>      pass
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>   yield server.close()
</I>&gt;&gt;<i>   yield client.close()
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> The test method executes and returns successfully. The exception is
</I>&gt;&gt;<i> raised and caught correctly, but because a
</I>&gt;&gt;<i> twisted.python.failure.Failure object was seen during deferred
</I>&gt;&gt;<i> processing, twisted.trial.unittest.TestCase._cleanUp() concludes that
</I>&gt;&gt;<i> an error occurred. That is perhaps not the most accurate way of
</I>&gt;&gt;<i> describing what happens, but the end result is that a caught  
</I>&gt;&gt;<i> exception
</I>&gt;&gt;<i> ends up being reported as an error.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> My question is this: are there any tips for performing exception
</I>&gt;&gt;<i> handling in test methods that are decorated with @inlineCallbacks? I
</I>&gt;&gt;<i> have been tracing through a lot of code trying to find any extension
</I>&gt;&gt;<i> point, hook, etc. where I could indicate that the exception was  
</I>&gt;&gt;<i> caught
</I>&gt;&gt;<i> correctly, but I have not found anything yet. Adding the obvious
</I>&gt;&gt;<i> @raises decoration does not work because the method catches the
</I>&gt;&gt;<i> exception. The closest I have come is to call
</I>&gt;&gt;<i> self._observer._ignoreErrors() from the test method with the  
</I>&gt;&gt;<i> exception
</I>&gt;&gt;<i> type in question, but that does not strike me as being on the right
</I>&gt;&gt;<i> track.
</I>&gt;<i>
</I>&gt;<i> If the problem is because the server code uses  
</I>&gt;<i> `twisted.python.log.err`
</I>&gt;<i> to log the double client connection attempt, then you can make it so
</I>&gt;<i> that this doesn't fail the test by flushing the error before the test
</I>&gt;<i> returns, with something like this:
</I>&gt;<i>
</I>&gt;<i>    self.flushLoggedErrors(UsernameAlreadyExists)
</I>&gt;<i>
</I>&gt;<i> Or possibly a different exception type, depending on what exactly the
</I>&gt;<i> server is logging.
</I>
That did it. Thanks!

  -Patrick

&gt;<i> If the server isn't logging anything, then I can't really know why  
</I>&gt;<i> your
</I>&gt;<i> test is failing based on the example you've given.  If you can  
</I>&gt;<i> construct
</I>&gt;<i> a SSCCE (&lt;<A HREF="http://sscce.org">http://sscce.org</A>&gt;), that would help a lot.
</I>&gt;<i>
</I>&gt;<i> Jean-Paul
</I>&gt;<i>
</I>&gt;<i> _______________________________________________
</I>&gt;<i> Twisted-Python mailing list
</I>&gt;<i> <A HREF="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">Twisted-Python at twistedmatrix.com</A>
</I>&gt;<i> <A HREF="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python</A>
</I>
--
Patrick L. Hartling
Senior Software Engineer, Priority 5
<A HREF="http://www.priority5.com/">http://www.priority5.com/</A>

The information transmitted in this communication is intended only for
the person or entity to which it is addressed and contains proprietary
material. Any review, retransmission, dissemination or other use of, or
taking of any action in reliance upon, this information by persons or
entities other than the intended recipient is prohibited. If you
received this in error, please destroy any copies, contact the sender
and delete the material from any computer.



</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message (by thread): <A HREF="053014.html">[Twisted-Python] Unit tests, inline callbacks,	and exception handling
</A></li>
	<LI>Next message (by thread): <A HREF="053016.html">[Twisted-Python] Unit tests, inline callbacks,	and exception handling
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#53015">[ date ]</a>
              <a href="thread.html#53015">[ thread ]</a>
              <a href="subject.html#53015">[ subject ]</a>
              <a href="author.html#53015">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
