<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] Problem exiting script that calls a func returning	a called deferred
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20Problem%20exiting%20script%20that%20calls%20a%20func%20returning%0A%09a%20called%20deferred&In-Reply-To=%3C18449.39933.404142.47145%40jon.es%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=utf-8">
   <LINK REL="Previous"  HREF="050097.html">
   <LINK REL="Next"  HREF="050099.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] Problem exiting script that calls a func returning	a called deferred</H1>
    <B>Terry Jones</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20Problem%20exiting%20script%20that%20calls%20a%20func%20returning%0A%09a%20called%20deferred&In-Reply-To=%3C18449.39933.404142.47145%40jon.es%3E"
       TITLE="[Twisted-Python] Problem exiting script that calls a func returning	a called deferred">terry at jon.es
       </A><BR>
    <I>Fri Apr 25 02:53:17 MDT 2008</I>
    <P><UL>
        <LI>Previous message (by thread): <A HREF="050097.html">[Twisted-Python] Forcing telnet connections to character mode	using twisted.conch.telnet.Telnet
</A></li>
        <LI>Next message (by thread): <A HREF="050099.html">[Twisted-Python] Problem exiting script that calls a func	returning a called deferred
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#50098">[ date ]</a>
              <a href="thread.html#50098">[ thread ]</a>
              <a href="subject.html#50098">[ subject ]</a>
              <a href="author.html#50098">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>&gt;<i>From searching and reading the list archives, I know the following comes up
</I>under various guises, and although I think I understand what's going on, I
don't see a nice solution.

I'm trying to write a standalone script. It calls externalFunc, a function
someone else wrote that returns a deferred. My script could look something
like this:

    from twisted.internet import reactor
    from twisted.python import log

    if __name__ == '__main__':
        def ok(result):
            print &quot;ok called with&quot;, result
        def nok(failure):
            print &quot;nok called with&quot;, failure
            return failure
        def stop(x):
            reactor.stop()

        d = externalFunc()
        d.addCallback(ok)
        d.addErrback(nok)
        d.addBoth(stop)
        d.addErrback(log.err)
        reactor.run()

And that works fine.

Now suppose I want to do some testing in which I swap out the external
function for a library I wrote myself (or for another implementation).  In
the testing library, externalFunc is simplified and uses defer.success() to
return its result.

In this case the script raises RuntimeError, &quot;can't stop reactor that isn't
running&quot; because the deferred that comes back from externalFunc has already
been called. So when I add the call/errbacks, they are fired right away and
the reactor isn't running when the stop function tries to stop it.

And script never exits because it then starts the reactor.

At this point there are various contortions I can try. Catching the
RuntimeError works, but the script never exits. Catching the RuntimeError
and then calling sys.exit doesn't work because sys.exit raises SystemExit
and that is caught in twisted/internet/defer.py _runCallbacks.

Supposing I had more control, the calling function could create the
deferred, pause it, pass it to externalFunc, add callbacks, then unpause.
But that doesn't work either as the callbacks fire as soon as unpause is
called, and you get the reactor not started error, followed by no exit as
you then start the reactor.

Testing reactor.running before trying to stop it in stop gets rid of the
error, but the reactor is then started and not stopped.

The only bulletproof way to deal with this that I've come up with is to
call self.fireSystemEvent(&quot;shutdown&quot;) but that feels wrong.

Several solutions seem possible with changes to Twisted: don't catch
SystemExit; give reactor.stop a (default False) keyword arg to tell it to
ignore a stopped reactor; stop deferreds from firing call/err backs if they
are paused (IMO it's a bit non-paradigmatic to have call/errback events
firing when the reactor isn't even running), etc.

I suppose I'm just not doing things right. Can someone tell me how I should
be doing this?

Terry


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message (by thread): <A HREF="050097.html">[Twisted-Python] Forcing telnet connections to character mode	using twisted.conch.telnet.Telnet
</A></li>
	<LI>Next message (by thread): <A HREF="050099.html">[Twisted-Python] Problem exiting script that calls a func	returning a called deferred
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#50098">[ date ]</a>
              <a href="thread.html#50098">[ thread ]</a>
              <a href="subject.html#50098">[ subject ]</a>
              <a href="author.html#50098">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
