<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] eated traceback when decorate method already	decorated by inlineCallbacks
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20eated%20traceback%20when%20decorate%20method%20already%0A%09decorated%20by%20inlineCallbacks&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="026666.html">
   <LINK REL="Next"  HREF="026671.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] eated traceback when decorate method already	decorated by inlineCallbacks</H1>
    <B>Sergey Gerasimov</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20eated%20traceback%20when%20decorate%20method%20already%0A%09decorated%20by%20inlineCallbacks&In-Reply-To="
       TITLE="[Twisted-Python] eated traceback when decorate method already	decorated by inlineCallbacks">sergun at gmail.com
       </A><BR>
    <I>Thu Mar 14 05:40:29 EDT 2013</I>
    <P><UL>
        <LI>Previous message: <A HREF="026666.html">[Twisted-Python] Twisted and serial port usage
</A></li>
        <LI>Next message: <A HREF="026671.html">[Twisted-Python] eated traceback when decorate method already decorated by inlineCallbacks
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#26667">[ date ]</a>
              <a href="thread.html#26667">[ thread ]</a>
              <a href="subject.html#26667">[ subject ]</a>
              <a href="author.html#26667">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hello to all!

Why traceback doesn't include call of g() here?

import traceback
from twisted.internet import defer, reactor

def decor1(f, *argv, **kw):
    @defer.inlineCallbacks
    def decor1():
        try:
            res = yield f(*argv, **kw)
            defer.returnValue(res)       
        except:
            traceback.print_exc()
    return decor1
    
@defer.inlineCallbacks
def g():
    raise AttributeError
    yield defer.succeed(1)

@decor1
@defer.inlineCallbacks
def f():
    yield g()   
    
f()
reactor.run()

I see just:
Traceback (most recent call last):
  File &quot;C:\testing\test.py&quot;, line 9, in decor1
    res = yield f(*argv, **kw)
AttributeError



</PRE>





<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="026666.html">[Twisted-Python] Twisted and serial port usage
</A></li>
	<LI>Next message: <A HREF="026671.html">[Twisted-Python] eated traceback when decorate method already decorated by inlineCallbacks
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#26667">[ date ]</a>
              <a href="thread.html#26667">[ thread ]</a>
              <a href="subject.html#26667">[ subject ]</a>
              <a href="author.html#26667">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
