<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] Understanding deferred and error handling
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20Understanding%20deferred%20and%20error%20handling&In-Reply-To=4DAF186B.5000000%40imperial.ac.uk">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="023899.html">
   <LINK REL="Next"  HREF="023901.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] Understanding deferred and error handling</H1>
    <B>David Cournapeau</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20Understanding%20deferred%20and%20error%20handling&In-Reply-To=4DAF186B.5000000%40imperial.ac.uk"
       TITLE="[Twisted-Python] Understanding deferred and error handling">cournape at gmail.com
       </A><BR>
    <I>Wed Apr 20 21:04:20 EDT 2011</I>
    <P><UL>
        <LI>Previous message: <A HREF="023899.html">[Twisted-Python] Understanding deferred and error handling
</A></li>
        <LI>Next message: <A HREF="023901.html">[Twisted-Python] Understanding deferred and error handling
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#23900">[ date ]</a>
              <a href="thread.html#23900">[ thread ]</a>
              <a href="subject.html#23900">[ subject ]</a>
              <a href="author.html#23900">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>On Thu, Apr 21, 2011 at 2:31 AM, Phil Mayers &lt;<A HREF="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">p.mayers at imperial.ac.uk</A>&gt; wrote:
&gt;<i> On 04/20/2011 05:28 AM, David wrote:
</I>&gt;&gt;<i> Hi,
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> I have a hard time figuring out error handling with deferred in twisted.
</I>&gt;&gt;<i> More exactly, I don't understand how to always get meaningful tracebacks
</I>&gt;&gt;<i> to understand where the error actually happened. For a simple example:
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> import sys
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> import twisted.web.client
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> from twisted.internet import defer
</I>&gt;&gt;<i> from twisted.internet import reactor
</I>&gt;&gt;<i> from twisted.python import log
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> def remote_call():
</I>&gt;&gt;<i> &#160; &#160; &#160; # No process bound to 8083 -&gt; &#160;connection refused
</I>&gt;&gt;<i> &#160; &#160; &#160; d = twisted.web.client.getPage(&quot;<A HREF="http://localhost:8083&quot;">http://localhost:8083&quot;</A>)
</I>&gt;&gt;<i> &#160; &#160; &#160; return d
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> def main():
</I>&gt;&gt;<i> &#160; &#160; &#160; d = remote_call()
</I>&gt;&gt;<i> &#160; &#160; &#160; def _stop(arg):
</I>&gt;&gt;<i> &#160; &#160; &#160; &#160; &#160; reactor.stop()
</I>&gt;&gt;<i> &#160; &#160; &#160; d.addBoth(_stop)
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> log.startLogging(sys.stdout)
</I>&gt;&gt;<i> reactor.callWhenRunning(main)
</I>&gt;&gt;<i> reactor.run()
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> This will simply print no error in the log:
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> 2011-04-20 12:37:40+0900 [-] Log opened.
</I>&gt;&gt;<i> 2011-04-20 12:37:40+0900 [-] Starting factory&lt;HTTPClientFactory:
</I>&gt;&gt;<i> <A HREF="http://localhost:8083">http://localhost:8083</A>&gt;
</I>&gt;&gt;<i> 2011-04-20 12:37:40+0900 [HTTPPageGetter,client] Stopping factory
</I>&gt;&gt;<i> &lt;HTTPClientFactory: <A HREF="http://localhost:8083">http://localhost:8083</A>&gt;
</I>&gt;&gt;<i> 2011-04-20 12:37:40+0900 [-] Main loop terminated.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> This already bothers me at a fundamental level, because it means it is
</I>&gt;&gt;<i> very easy to &quot;swallow&quot; errors without being aware of it. Is there a
</I>&gt;&gt;<i> &quot;systematic&quot; solution to this issue, or am I condemned to handle errors
</I>&gt;&gt;<i> systematically everywhere in my code ?
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Now, if I add an errback for logging purpose:
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> def main():
</I>&gt;&gt;<i> &#160; &#160; &#160; d = remote_call()
</I>&gt;&gt;<i> &#160; &#160; &#160; def _stop(arg):
</I>&gt;&gt;<i> &#160; &#160; &#160; &#160; &#160; reactor.stop()
</I>&gt;&gt;<i> &#160; &#160; &#160; d.addErrback(log.err)
</I>&gt;&gt;<i> &#160; &#160; &#160; d.addBoth(_stop)
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> I get something like:
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> 2011-04-20 12:38:35+0900 [-] Log opened.
</I>&gt;&gt;<i> 2011-04-20 12:38:35+0900 [-] Starting factory&lt;HTTPClientFactory:
</I>&gt;&gt;<i> <A HREF="http://localhost:8083">http://localhost:8083</A>&gt;
</I>&gt;&gt;<i> 2011-04-20 12:38:35+0900 [HTTPPageGetter,client] Unhandled Error
</I>&gt;&gt;<i> &#160; &#160; &#160; Traceback (most recent call last):
</I>&gt;&gt;<i> &#160; &#160; &#160; Failure: twisted.web.error.Error: 404 Not Found
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> 2011-04-20 12:38:35+0900 [HTTPPageGetter,client] Stopping factory
</I>&gt;&gt;<i> &lt;HTTPClientFactory: <A HREF="http://localhost:8083">http://localhost:8083</A>&gt;
</I>&gt;&gt;<i> 2011-04-20 12:38:35+0900 [-] Main loop terminated.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> I do get an error, but I don't get a traceback. Interestingly enough, if
</I>&gt;&gt;<i> I use printTraceback:
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> def main():
</I>&gt;&gt;<i> &#160; &#160; &#160; d = remote_call()
</I>&gt;&gt;<i> &#160; &#160; &#160; def _stop(arg):
</I>&gt;&gt;<i> &#160; &#160; &#160; &#160; &#160; reactor.stop()
</I>&gt;&gt;<i> &#160; &#160; &#160; def log_error(failure):
</I>&gt;&gt;<i> &#160; &#160; &#160; &#160; &#160; log.err(failure.printTraceback())
</I>&gt;&gt;<i> &#160; &#160; &#160; &#160; &#160; return failure
</I>&gt;&gt;<i> &#160; &#160; &#160; d.addErrback(log_error)
</I>&gt;&gt;<i> &#160; &#160; &#160; d.addBoth(_stop)
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> I don't get any traceback either.
</I>&gt;<i>
</I>&gt;<i> As other people have pointed out, you're discarding the failure.
</I>
Indeed, I forgot to return the argument in my _stop callback. This answers part
of my question, but not what I consider the meat of my issue, that is
the lack of traceback. Fixing and simplifying my initial example:

import twisted.web.client

from twisted.internet import defer
from twisted.internet import reactor

def remote_call():
    d = twisted.web.client.getPage(&quot;<A HREF="http://localhost:8083&quot;">http://localhost:8083&quot;</A>)
    return d

def main():
    d = remote_call()
    def _stop(arg):
        reactor.stop()
        return arg
    d.addBoth(_stop)

reactor.callWhenRunning(main)
reactor.run()

This will correctly signal an error, but the output:

Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
Failure: twisted.internet.error.ConnectionRefusedError: Connection was
refused by other side: 61: Connection refused.

is not informative. I was hoping for a way to know that the error
happens inside remote_call through e.g. an errback in main. If this is
not possible, how do people generally handle those issues in
asynchronous code ?

cheers,

David

</PRE>














<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="023899.html">[Twisted-Python] Understanding deferred and error handling
</A></li>
	<LI>Next message: <A HREF="023901.html">[Twisted-Python] Understanding deferred and error handling
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#23900">[ date ]</a>
              <a href="thread.html#23900">[ thread ]</a>
              <a href="subject.html#23900">[ subject ]</a>
              <a href="author.html#23900">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
