<tt>
I´ve&nbsp;observed&nbsp;the&nbsp;same&nbsp;error&nbsp;when&nbsp;playing&nbsp;around&nbsp;with&nbsp;twisted&nbsp;behind&nbsp;a&nbsp;reverse&nbsp;proxy&nbsp;(apache/nginx). &nbsp;Are&nbsp;your&nbsp;conditions&nbsp;similar?&lt;br&gt;&lt;br&gt;&lt;div&nbsp;class=&quot;gmail_quote&quot;&gt;On&nbsp;Tue,&nbsp;Jul&nbsp;7,&nbsp;2009&nbsp;at&nbsp;8:58&nbsp;PM,&nbsp;Paul&nbsp;Reznicek&nbsp;&lt;span&nbsp;dir=&quot;ltr&quot;&gt;&amp;lt;&lt;a&nbsp;href=&quot;mailto:maillists@ivsn.com&quot;&gt;maillists@ivsn.com&lt;/a&gt;&amp;gt;&lt;/span&gt;&nbsp;wrote:&lt;br&gt;<br>
&lt;blockquote&nbsp;class=&quot;gmail_quote&quot;&nbsp;style=&quot;border-left:&nbsp;1px&nbsp;solid&nbsp;rgb(204,&nbsp;204,&nbsp;204);&nbsp;margin:&nbsp;0pt&nbsp;0pt&nbsp;0pt&nbsp;0.8ex;&nbsp;padding-left:&nbsp;1ex;&quot;&gt;Hello,&lt;br&gt;<br>
I&nbsp;observe&nbsp;this&nbsp;error&nbsp;few&nbsp;times&nbsp;a&nbsp;day&nbsp;and&nbsp;have&nbsp;no&nbsp;idea&nbsp;about&nbsp;what&nbsp;is&nbsp;causing&lt;br&gt;<br>
it,&nbsp;neither&nbsp;under&nbsp;which&nbsp;conditions&nbsp;it&nbsp;happen&nbsp;(Nevow-0.9.33):&lt;br&gt;<br>
&lt;br&gt;<br>
Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):&lt;br&gt;<br>
&nbsp; &nbsp;File&nbsp;&amp;quot;/usr/lib/python2.6/dist-packages/twisted/internet/defer.py&amp;quot;,&nbsp;line&nbsp;195,&nbsp;in&nbsp;addCallback&lt;br&gt;<br>
&nbsp; &nbsp; &nbsp;callbackKeywords=kw)&lt;br&gt;<br>
&nbsp; &nbsp;File&nbsp;&amp;quot;/usr/lib/python2.6/dist-packages/twisted/internet/defer.py&amp;quot;,&nbsp;line&nbsp;186,&nbsp;in&lt;br&gt;<br>
addCallbacks&lt;br&gt;<br>
&nbsp; &nbsp; &nbsp;self._runCallbacks()&lt;br&gt;<br>
&nbsp; &nbsp;File&nbsp;&amp;quot;/usr/lib/python2.6/dist-packages/twisted/internet/defer.py&amp;quot;,&nbsp;line&nbsp;328,&nbsp;in&lt;br&gt;<br>
_runCallbacks&lt;br&gt;<br>
&nbsp; &nbsp; &nbsp;self.result&nbsp;=&nbsp;callback(self.result,&nbsp;*args,&nbsp;**kw)&lt;br&gt;<br>
&nbsp; &nbsp;File&nbsp;&amp;quot;/usr/local/lib/python2.6/dist-packages/nevow/appserver.py&amp;quot;,&nbsp;line&nbsp;163,&nbsp;in&lt;br&gt;<br>
gotPageContext&lt;br&gt;<br>
&nbsp; &nbsp; &nbsp;pageContext.tag.renderHTTP,&nbsp;pageContext&lt;br&gt;<br>
---&nbsp;&amp;lt;exception&nbsp;caught&nbsp;here&amp;gt;&nbsp;---&lt;br&gt;<br>
&nbsp; &nbsp;File&nbsp;&amp;quot;/usr/lib/python2.6/dist-packages/twisted/internet/defer.py&amp;quot;,&nbsp;line&nbsp;106,&nbsp;in&lt;br&gt;<br>
maybeDeferred&lt;br&gt;<br>
&nbsp; &nbsp; &nbsp;result&nbsp;=&nbsp;f(*args,&nbsp;**kw)&lt;br&gt;<br>
&nbsp; &nbsp;File&nbsp;&amp;quot;/usr/local/lib/python2.6/dist-packages/nevow/athena.py&amp;quot;,&nbsp;line&nbsp;440,&nbsp;in&nbsp;renderHTTP&lt;br&gt;<br>
&nbsp; &nbsp; &nbsp;messageData&nbsp;=&nbsp;json.parse(requestContent)&lt;br&gt;<br>
&nbsp; &nbsp;File&nbsp;&amp;quot;/usr/local/lib/python2.6/dist-packages/nevow/json.py&amp;quot;,&nbsp;line&nbsp;228,&nbsp;in&nbsp;parse&lt;br&gt;<br>
&nbsp; &nbsp; &nbsp;value,&nbsp;tokens&nbsp;=&nbsp;parseValue(tokens)&lt;br&gt;<br>
&nbsp; &nbsp;File&nbsp;&amp;quot;/usr/local/lib/python2.6/dist-packages/nevow/json.py&amp;quot;,&nbsp;line&nbsp;130,&nbsp;in&nbsp;parseValue&lt;br&gt;<br>
&nbsp; &nbsp; &nbsp;if&nbsp;tokens[0]&nbsp;==&nbsp;&amp;#39;{&amp;#39;:&lt;br&gt;<br>
exceptions.IndexError:&nbsp;list&nbsp;index&nbsp;out&nbsp;of&nbsp;range&lt;br&gt;<br>
&lt;br&gt;<br>
I&nbsp;asked&nbsp;some&nbsp;user,&nbsp;but&nbsp;nobody&nbsp;observed&nbsp;problems&nbsp;on&nbsp;the&nbsp;user&nbsp;site,&lt;br&gt;<br>
any&nbsp;idea,&nbsp;what&nbsp;is&nbsp;wrong?&lt;br&gt;<br>
&lt;br&gt;<br>
Regards,&nbsp;Paul&lt;br&gt;<br>
&lt;br&gt;<br>
_______________________________________________&lt;br&gt;<br>
Twisted-web&nbsp;mailing&nbsp;list&lt;br&gt;<br>
&lt;a&nbsp;href=&quot;mailto:Twisted-web@twistedmatrix.com&quot;&gt;Twisted-web@twistedmatrix.com&lt;/a&gt;&lt;br&gt;<br>
&lt;a&nbsp;href=&quot;http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-web&quot;&nbsp;target=&quot;_blank&quot;&gt;http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-web&lt;/a&gt;&lt;br&gt;<br>
&lt;/blockquote&gt;&lt;/div&gt;&lt;br&gt;<br>

</tt>
