<tt>
&lt;div&nbsp;dir=&quot;ltr&quot;&gt;I&#39;m&nbsp;continuing to&nbsp;wrestle&nbsp;with&nbsp;conch,&nbsp;this&nbsp;time&nbsp;around&nbsp;authentication&nbsp;and&nbsp;notifying&nbsp;deferred&nbsp;of&nbsp;auth&nbsp;failure. &lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;It&nbsp;seems&nbsp;like&nbsp;the&nbsp;SSH&nbsp;factory&nbsp;has&nbsp;a&nbsp;deferred&nbsp;to&nbsp;be&nbsp;notified&nbsp;of&nbsp;auth&nbsp;failures&nbsp;here:&lt;/div&gt;&lt;div&gt;&lt;a&nbsp;href=&quot;https://github.com/twisted/twisted/blob/trunk/src/twisted/conch/client/direct.py#L61-L66&quot;&gt;https://github.com/twisted/twisted/blob/trunk/src/twisted/conch/client/direct.py#L61-L66&lt;/a&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Unfortunately,&nbsp;this&nbsp;deferred&nbsp;is&nbsp;cleared&nbsp;because&nbsp;prior&nbsp;to&nbsp;auth,&nbsp;it&nbsp;receives this&nbsp;on&nbsp;successful&nbsp;connect:&lt;br&gt;&lt;a&nbsp;href=&quot;https://github.com/twisted/twisted/blob/trunk/src/twisted/conch/client/direct.py#L83-L88&quot;&gt;https://github.com/twisted/twisted/blob/trunk/src/twisted/conch/client/direct.py#L83-L88&lt;/a&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;As&nbsp;you&nbsp;can&nbsp;see&nbsp;this&nbsp;clears&nbsp;the&nbsp;deferred&nbsp;so&nbsp;it&nbsp;is&nbsp;no&nbsp;longer&nbsp;available&nbsp;to&nbsp;get&nbsp;an&nbsp;errback.&nbsp;This&nbsp;also&nbsp;prevents&nbsp;the&nbsp;SSHClientTransport&nbsp;from&nbsp;getting&nbsp;a&nbsp;sendDisconnect. &lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;To&nbsp;try&nbsp;it&nbsp;change&nbsp;the&nbsp;user&nbsp;to&nbsp;something&nbsp;invalid&nbsp;here: &lt;a&nbsp;href=&quot;https://gist.github.com/radifalco/5a5cca4bf8d49d5c61113e36f9be7553#file-sftp-py-L328&quot;&gt;https://gist.github.com/radifalco/5a5cca4bf8d49d5c61113e36f9be7553#file-sftp-py-L328&lt;/a&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;This&nbsp;will&nbsp;never&nbsp;get&nbsp;a&nbsp;callback&nbsp;to&nbsp;errback. &lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;I&nbsp;guess&nbsp;I&nbsp;would&nbsp;have&nbsp;expected&nbsp;this&nbsp;to&nbsp;get&nbsp;the&nbsp;error&nbsp;but&nbsp;it&nbsp;actually&nbsp;succeeds&nbsp;with&nbsp;None.&nbsp;As&nbsp;a&nbsp;result&nbsp;there&nbsp;is&nbsp;no&nbsp;deferred&nbsp;to&nbsp;get&nbsp;the&nbsp;auth&nbsp;failure&nbsp;and&nbsp;my&nbsp;app&nbsp;waits&nbsp;forever&nbsp;for&nbsp;a&nbsp;notification. &lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;There&nbsp;is&nbsp;one&nbsp;ting&nbsp;I&nbsp;*think*&nbsp;I&nbsp;know&nbsp;how&nbsp;to&nbsp;do,&nbsp;add&nbsp;a&nbsp;timeout&nbsp;with&nbsp;a&nbsp;callback&nbsp;later&nbsp;on&nbsp;the&nbsp;sftpClient&nbsp;deferred.&nbsp;But&nbsp;that&nbsp;seems&nbsp;lame.&nbsp;What&nbsp;I&#39;d&nbsp;like&nbsp;to&nbsp;do&nbsp;is&nbsp;to&nbsp;get&nbsp;this&nbsp;ConchError&nbsp;as&nbsp;it&nbsp;has&nbsp;the&nbsp;actual&nbsp;reason&nbsp;for&nbsp;the&nbsp;connection&nbsp;failure. &nbsp;Thoughts?&lt;br&gt;&lt;br&gt;&lt;a&nbsp;href=&quot;https://github.com/twisted/twisted/blob/trunk/src/twisted/conch/client/direct.py#L61-L66&quot;&gt;https://github.com/twisted/twisted/blob/trunk/src/twisted/conch/client/direct.py#L61-L66&lt;/a&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;/div&gt;<br>

</tt>
